### ISSUE TITLE
GitOps and the HashiStack

### ISSUE THREAD

**Issue by o6uoq** [gitops-working-group/gitops-working-group#4] opened 2021-01-06 21:24 UTC
👋🏼 I would like to be involved in the GitOps Working Group and also discuss formalising better patterns of integrating GitOps into Infrastructure-as-Code, combining patterns and how that can apply to the HashiStack (Terraform, Consul, Vault, Terraform Cloud).

Terraform Cloud has an incredible range of git integration and I think there's an opportunity to extend GitOps beyond just Kubernetes into other patterns (albeit as a venn vs outlying).

**Comment by o6uoq** [comment] 2021-01-06 21:24
[GitOps Principles](https://www.weave.works/blog/announcing-gitops-working-group) state:

**The Five GitOps Principles are as follows:**

**1. Declarative Configuration:** All resources managed through a GitOps process must be completely expressed declaratively.

**2. Version controlled, immutable storage:** Declarative descriptions are stored in a repository that supports immutability, versioning and version history. For example, git.

**3. Automated delivery:** Delivery of the declarative descriptions, from the repository to runtime environment, is fully automated.

**4. Software Agents:** Reconcilers maintain system state and apply the resources described in the declarative configuration.

**5. Closed loop:** Actions are performed on divergence between the version controlled declarative configuration and the actual state of the target system.

HashiStack is declarative and driven by VCS (version controlled + immutable storage), automated delivery either through DIY CI/CD or Terraform Cloud, leaving the only unfulfilled requirements to be within the venn of GitOps is both `[4]` and `[5]`.

**Comment by scottrigby** [comment] 2021-01-20 20:31
Closing as a duplicate of #5 since that has these same comments plus more discussion 🙂

**Closed by scottrigby** 2021-01-20 20:31 UTC
Labels: duplicate
